spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://124.221.242.250:3306/partermatch?useSSL=false'
    username: parter
    password: abc123
  # session 失效时间
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: 124.221.242.250
    database: 1
    password: abc123
server:
  address: 0.0.0.0
  port: 8081
  servlet:
    context-path: /api
    session:
      cookie:
        domain: 124.221.242.250
        same-site: lax
        secure: false